[package]
name = "rs-a"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
num = "0.4.3"
num-bigint = { version = "0.4.3", features=["rand"]}
rand = { version = "0.8.5", features=["getrandom"] }
rand_chacha = "0.3.1"
